spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tL47i4wo3osGwRjGNN1
      secret-key: FEKX5kgYivT9np6fpT2ZZjBrTviTn5
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-fengling

  application:
    name: gulimall-third-party

server:
  port: 30000
